### ISSUE TITLE
How to test the program?

### ISSUE THREAD

**Issue by EmmanuelSantiago** [ObieG/analyzing_baseball_data#1]
hi i am trying to understand your code but i want to test it, how do i do? for example:
def filter_by_year(statistics, year, yearid):
    """
    Inputs:
      statistics - List of batting statistics dictionaries
      year       - Year to filter by
      yearid     - Year ID field in statistics
    Outputs:
      Returns a list of batting statistics dictionaries that
      are from the input year.
    """
    year_list = []

    for row in statistics:

        #Realiza una comparacion del yearID con respecto al año buscado si comple lo añade a la nueva lista
        if int(row[yearid]) == year:
            year_list.append(row)
    return year_list

In this function what are the parameters,statistics, year and yearid; i know it said in inputs but i cant make it show me the list.

**Comment by EmmanuelSantiago** [comment]
it keep giving me this error:
Traceback (most recent call last):
  File "C:\Users\hello.py", line 134, in <module>
    print(filter_by_year(stats_list, 1971, 1971))
  File "C:\Users\hello.py", line 131, in filter_by_year
    if int(row[yearid]) == year:
KeyError: 1971
